version: '2.1'

services:
  app:
    image: flask-server
    container_name: flask-server
    build: .
    ports:
      - 3001:3000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
    networks:
      - back-end

  os:
    image: ubuntu:16.04
    container_name: ubuntu
    depends_on:
      app:
        condition: service_healthy
    networks:
      - back-end
    command: ['sleep', '120']

networks:
  back-end:
  front-end:
