version: '2.1'

services:
  app:
    image: flask-server
    container_name: flask-server
    build: .
    ports:
      - 3001:3000

  os:
    image: ubuntu:16.04
    container_name: ubuntu
    command: ['sleep', '5000']
